# Generated by Django 5.2.7 on 2025-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factura", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="iva",
            new_name="imp_consumo_valor",
        ),
        migrations.RenameField(
            model_name="factura",
            old_name="total",
            new_name="iva_valor",
        ),
        migrations.RenameField(
            model_name="factura",
            old_name="total_con_iva",
            new_name="total_con_impuestos",
        ),
        migrations.AddField(
            model_name="factura",
            name="imp_consumo_porcentaje",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="factura",
            name="iva_porcentaje",
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="factura",
            name="retefuente_porcentaje",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="factura",
            name="retefuente_valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
