# Generated by Django 5.2.7 on 2025-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factura", "0002_rename_iva_factura_imp_consumo_valor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="documento_identidad",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
