# Generated by Django 5.2.7 on 2025-10-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factura", "0003_cliente_documento_identidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="EMPRESA XYZ LTDA", max_length=200),
                ),
                ("nit", models.CharField(default="901.234.567-8", max_length=20)),
                (
                    "direccion",
                    models.TextField(default="Calle 123 #45-67, Bogotá, Colombia"),
                ),
                (
                    "telefono",
                    models.CharField(default="+57 300 123 4567", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        default="facturacion@empresa.com", max_length=254
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
