# Generated by Django 5.2.7 on 2025-10-09 23:38

import factura.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factura", "0004_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("CE", "Cédula de Extranjería"),
                    ("NIT", "NIT"),
                    ("PASAPORTE", "Pasaporte"),
                    ("OTRO", "Otro"),
                ],
                default="CC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="documento_identidad",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[factura.validators.validar_documento_colombiano],
            ),
        ),
    ]
